--- # Generador Qr
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generador-qr
  namespace: bienal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generador-qr
  template:
    metadata:
      labels:
        app: generador-qr
    spec:
      containers:
      - name: generador-qr-container
        image: stefanomerinoderui/bienal-backend:generadorQr
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri    # Nombre del Secret
              key: MONGODB_URI   # Clave en el Secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: qr-secret-key
              key: SECRET_KEY
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: FRONTEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: generador-qr
  namespace: bienal-backend
spec:
  selector:
    app: generador-qr
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Permite que el tráfico de salida sea accesible desde el cluster