--- # Buscador
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buscador
  namespace: bienal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buscador
  template:
    metadata:
      labels:
        app: buscador
    spec:
      containers:
      - name: buscador-container
        image: stefanomerinoderui/bienal-backend:buscador
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "80"
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri    # Nombre del Secret
              key: MONGODB_URI   # Clave en el Secret
---
apiVersion: v1
kind: Service
metadata:
  name: buscador
  namespace: bienal-backend
spec:
  selector:
    app: buscador
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Permite que el tráfico de salida sea accesible desde el cluster