services:
  api_gateway:
    build:
      context: ./../apiGateway
      dockerfile: docker/Dockerfile
      args:
          EXPRESS_PORT: 80
    image: ${DOCKER_REPO_NAME}:api_gateway${DOCKER_TAG_EXTRA}
  gestion_escultores:
    build:
      context: ./../ModuloGestion/ServicioGestionEscultores
      dockerfile: docker/Dockerfile
      args:
        EXPRESS_PORT: 80
    image: ${DOCKER_REPO_NAME}:gestion_escultores${DOCKER_TAG_EXTRA}
  gestion_esculturas:
    build:
      context: ./../ModuloGestion/ServicioGestionEsculturas
      dockerfile: docker/Dockerfile
      args:
        EXPRESS_PORT: 80
    image: ${DOCKER_REPO_NAME}:gestion_esculturas${DOCKER_TAG_EXTRA}
  gestion_eventos:
    build:
      context: ./../ModuloGestion/ServicioGestionEventos
      dockerfile: docker/Dockerfile
      args:
        EXPRESS_PORT: 80
    image: ${DOCKER_REPO_NAME}:gestion_eventos${DOCKER_TAG_EXTRA}
  autorizacion:
    build:
      context: ./../ModuloVotYVal/ServicioAuth
      dockerfile: docker/Dockerfile
      args:
        EXPRESS_PORT: 80
    image: ${DOCKER_REPO_NAME}:autorizacion${DOCKER_TAG_EXTRA}
  registro_votos:
    build:
      context: ./../ModuloVotYVal/ServicioVotacion
      dockerfile: docker/Dockerfile
      args:
        EXPRESS_PORT: 80
    image: ${DOCKER_REPO_NAME}:registro_votos${DOCKER_TAG_EXTRA}
  generadorQR:
    build:
      context: ./../ModuloVotYVal/ServicioQr
      dockerfile: docker/Dockerfile
      args:
        EXPRESS_PORT: 80
    image: ${DOCKER_REPO_NAME}:generadorQr${DOCKER_TAG_EXTRA}
  buscador:
    build:
      context: ./../ServicioBusqueda
      dockerfile: docker/Dockerfile
      args:
        EXPRESS_PORT: 80
    image: ${DOCKER_REPO_NAME}:buscador${DOCKER_TAG_EXTRA}