name: Deploy to EKS

on:
  pull_request:
    branches:
      - development  # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub using GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker Compose images
    - name: Build Docker Compose Images
      run: |
        DOCKER_REPO_NAME=stefanomerinoderui/bienal-backend
        DOCKER_TAG_EXTRA="development"
        docker compose -f docker/docker-compose.yml build
    # Push Docker Compose images
    - name: Push Docker Compose Images
      run: |
        DOCKER_REPO_NAME=stefanomerinoderui/bienal-backend
        DOCKER_TAG_EXTRA="development"
        docker compose -f docker/docker-compose.yml push

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::043309323626:role/BienalBackend-githubAction-development
        aws-region: sa-east-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Configure kubectl for EKS cluster
      run: |
        aws eks update-kubeconfig --region sa-east-1 --name Bienal_backend_development

    - name: Apply Kubernetes config
      run: |
        kubectl apply -f ./docker/kubernetes/kubernetes_*.yml
    
    - name: Log Kubernetes
      run: |
        kubectl get pods
        echo "Hostname service:"
        kubectl get service api-gateway -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}'
    
    - name: Apply Kubernetes config
      run: |
        kubectl config set-context --current --namespace=bienal-backend
        kubectl apply -f ./docker/kubernetes/kubernetes_*.yml
        kubectl rollout restart deployment api-gateway gestion-esculturas gestion-escultores gestion-eventos generador-qr registro-votos